Better document load_from_checkpoint
vitalab/vital pull request #128
Opened 2022-11-19 00:11 UTC by lemairecarl

I consider this a WIP, your comments/suggestions/commits are welcome!

* I think using "model" in this context is confusing. In `vital`, a "system" is a LightningModule, and a "model" is a nn.Module. But I guess it's fine to call a checkpoint a (saved) model, so that's why I left "model" in the exception message. That's totally arbitrary. :)
* I tried to dissipate some confusion about the type of objects we are dealing with. This version seems better to me, but you might not agree. Suggestions are welcome.

2022-11-19 11:41 UTC, nathanpainchaud requested changes
Thanks for the PR! Everything seems good to me, I just jumped on the chance to correct a verb tense mistake that was already there :wink:

2022-11-19 11:41 UTC, nathanpainchaud commented on vital/utils/saving.py
> +        Lightning module (specifically a subclass of VitalSystem) loaded from the checkpoint, casted to its original
While we're at it, let's correct a verb tense mistake I left behind previously (the past tense of _to cast_ is simply _cast_):
```suggestion
        Lightning module (specifically a subclass of VitalSystem) loaded from the checkpoint, cast to its original
```

2022-11-22 18:04 UTC, lemairecarl commented
J'ai de plus en plus de questions...

* Pourquoi est-ce possible d'instancier `VitalSystem` ? Appeler son constructeur ne cause pas d'exception. Ça me semble contre-intuitif. Ça voudrait dire qu'ils n'y a pas d'abstractmethod (non-implémentées). Donc l'utilisation de `ABC` n'est que conceptuelle, elle n'a "pas de dents"?
* J'allais définir `VitalSystem.load_from_checkpoint` pour lever une exception... cependant ça casse tout! Parce qu'on dépend de l'implémentation du parent de `VitalSystem` (`LightningModule.load_from_checkpoint`). Je ne sais plus trop quoi faire maintenant.
* Est-ce une bonne idée de définir `VitalSystem.load_from_checkpoint`, et d'y vérifier si `cls` est une ABC, et seulement dans ce cas afficher une exception, sinon appeler l'implémentation du parent? Ça semble compliqué...
* Comment expliquer que j'aie eu le réflexe d'utiliser `VitalSystem.load_from_checkpoint`, et que c'est possible de l'appeler, mais que ce soit à ce point incompatible avec l'architecture actuelle... et que ça échoue avec un message d'erreur difficile à comprendre (`RuntimeError: Error(s) in loading state_dict for VitalSystem: Unexpected key(s) in state_dict`).
* J'ai eu l'idée d'utiliser l'implémentation de `vital.utils.saving.load_from_checkpoint` dans `VitalSystem.load_from_checkpoint`, mais ça cause une dépendance circulaire, parce que `vital.utils.saving.load_from_checkpoint` appelle `ConcreteSystem.load_from_checkpoint`, qui va utiliser `VitalSystem.load_from_checkpoint`. Wtf?

Donc voilà, ça va demander un peu plus de réflexion. Tes réflexions sont les bienvenues.

2022-11-22 20:06 UTC, lemairecarl commented
Finalement, je pense qu'une solution relativement simple serait d'implémenter un `VitalSystem.load_from_checkpoint` qui:

* Échoue si `cls == VitalSystem`
* Appelle `super().load_from_checkpoint` sinon

2022-11-22 20:23 UTC, nathanpainchaud commented
> Finalement, je pense qu'une solution relativement simple serait d'implémenter un `VitalSystem.load_from_checkpoint` qui:
> 
> * Échoue si `cls == VitalSystem`
> * Appelle `super().load_from_checkpoint` sinon

@lemairecarl C'est ce que j'ai déjà implémenté :wink: Avec la nuance que ce n'est pas seulement si `cls == VitalSystem`, mais plutôt si la classe à comme parent direct `ABC`, comme ça on inclut aussi d'autres classes "abstraites" de `vital` comme `SharedStepTask`.

Mais je me demandais justement si c'est qqch que je devrais pusher sur cette PR ou bien si on fait ça dans une PR séparée?

2022-11-22 20:39 UTC, lemairecarl commented
Oups! Je viens de voir ton commentaire, en retard. Ta solution est meilleure. Et effectivement, ça devrait aller dans un autre PR.

2022-11-22 20:41 UTC, lemairecarl commented
En fait, je te propose autre chose: Si `cls` n'est pas instanciable (car `VitalSystem` par exemple), on appelle `vital.utils.saving.load_from_checkpoint`. C'est ce que je viens de commiter ici.

2022-11-22 20:47 UTC, lemairecarl commented
@nathanpainchaud Je vais enlever le dernier commit quand tu m'auras confirmé que tu l'as vu

2022-11-22 20:50 UTC, nathanpainchaud commented
> @nathanpainchaud Je vais enlever le dernier commit quand tu m'auras confirmé que tu l'as vu

@lemairecarl Je l'ai bien vu :wink:

2022-11-23 08:32 UTC, nathanpainchaud approved these changes

2022-11-23 08:34 UTC, merged