Feature/refactor hydra yaml
vitalab/vital pull request #22
Opened 2021-06-15 20:36 UTC by ThierryJudge

**Add support for Hydra**

This PR add supports for Hydra with Yaml configs.

* Adds hydra config for segmentation and classification systems for mlp, unet and enet. 
* Adds support for python-dotenv to load system specific environment variables
* Adds examples on how to use vital submodule and hydra configs in other projects. 

Still needs to be done (in subsequent PRs): 
* Refactor readme
* Allow optimizer configuration
* Add missing configs for networks
* Add support for auto-encoders

2021-06-22 22:57 UTC, lemairecarl reviewed
Looks good, great work! Not yet finished, but I like the direction this is going into.

BTW, why does this other PR (still) exist? https://github.com/nathanpainchaud/vital/pull/19

2021-08-09 19:33 UTC, nathanpainchaud requested changes
Some minor final comments that can be fixed very easily. Otherwise, just 2 general things to do before merging:

1. I pushed some fixes for the Comet model registry query to the main dev branch. I suggest you merge those changes first;
2. Seems you're in conflict with the hydra branch you're merging into, so you should fix those!

2021-08-10 19:55 UTC, nathanpainchaud approved these changes

2021-08-11 15:44 UTC, merged

2021-08-11 16:04 UTC, lemairecarl reviewed
Oops, I "missed the deadline" of the merge of this PR! Sorry. (I was reviewing when it was merged.)

Anyways, it looks all good to me, except for one small thing.

Great work guys!